type: prose
color: "#a957b0"
title: ALA Annual 2018 MAGIRT Chair's Program
logo: /assets/img/logo.png
description: Come learn more about the spatial geo humanities in academic libraries
theme: jekyll-theme-minimal
